import axios from 'axios';

axios.defaults.withCredentials = false;
export const TOKEN_EXPIRED = 'TOKEN_EXPIRED';

// Signup Actions Types
export const REQUEST_SIGNUP_USER = 'REQUEST_REGISTER_USER';
export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';

// Signout Actions Types
export const SIGNOUT_USER = 'SIGNOUT_USER';

// Create Center Action Types
export const RECEIVED_CENTER_CONTACTS = 'RECEIVED_CENTER_CONTACTS';
export const FETCHING_CENTER_CONTACTS = 'FETCHING_CENTER_CONTACTS';

export const CREATING_NEW_CENTER = 'CREATING_NEW_CENTER';
export const CREATED_NEW_CENTER = 'CREATED_NEW_CENTER';
export const CREATING_NEW_CENTER_ERROR = 'CREATING_NEW_CENTER_ERROR';
export const RESET_CREATE_NEW_CENTER = 'RESET_CREATE_NEW_CENTER';

// List Centers
export const RECEIVED_CENTERS = 'RECEIVED_CENTERS';
export const FETCHING_CENTERS = 'FETCHING_CENTERS';

export const RECEIVED_CENTER = 'RECEIVED_CENTER';
export const FETCHING_CENTER = 'FETCHING_CENTER';

export const FETCHING_ADMIN_CENTERS = 'FETCHING_ADMIN_CENTERS';
export const RECEIVED_ADMIN_CENTERS = 'RECEIVED_ADMIN_CENTERS';
export const FETCHING_ADMIN_CENTERS_ERROR = 'FETCHING_ADMIN_CENTERS_ERROR';

export const FETCHING_CENTERS_EVENTS = 'FETCHING_CENTERS_EVENTS';
export const RECEIVED_CENTERS_EVENTS = 'RECEIVED_CENTERS_EVENTS';
export const FETCHING_CENTERS_EVENTS_ERRORS = 'FETCHING_CENTERS_EVENTS_ERRORS';

// Create Event
export const CREATED_EVENT = 'CREATED_EVENT';
export const REQUEST_CREATE_EVENT = 'REQUEST_CREATE_EVENT';
export const CREATE_EVENT_ERROR = 'CREATE_EVENT_ERROR';
// Get Events Actions
export const FETCHING_EVENTS = 'FETCHING_EVENTS';
export const RECEIVED_EVENTS = 'RECEIVED_EVENTS';
export const FETCHING_EVENTS_ERROR = 'EVENT_ERROR';

// Get User Actions
export const UPDATING_USER = 'UPDATING_USER';
export const UPDATED_USER = 'UPDATED_USER';
export const UPDATING_USER_ERROR = 'UPDATING_USER_ERROR';

export const REQUEST_SIGNIN_USER = 'REQUEST_SIGNIN_USER';
export const SIGNIN_USER = 'SIGNIN_USER';
export const SIGNIN_USER_ERROR = 'SIGNIN_USER_ERROR';
