export const TOKEN_EXPIRED = 'TOKEN_EXPIRED';

// Signup Actions Types
export const REQUEST_SIGNUP_USER = 'REQUEST_REGISTER_USER';
export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';

// Signout Actions Types
export const SIGNOUT_USER = 'SIGNOUT_USER';

// Create Center Action Types
export const RECEIVED_CENTER_CONTACTS = 'RECEIVED_CENTER_CONTACTS';
export const FETCHING_CENTER_CONTACTS = 'FETCHING_CENTER_CONTACTS';

// List Centers
export const RECEIVED_CENTERS = 'RECEIVED_CENTERS';
export const FETCHING_CENTERS = 'FETCHING_CENTERS';
export const RECEIVED_CENTER = 'RECEIVED_CENTER';
export const FETCHING_CENTER = 'FETCHING_CENTER';

// Create Event
export const CREATED_EVENT = 'CREATED_EVENT';
export const REQUEST_CREATE_EVENT = 'REQUEST_CREATE_EVENT';
export const CREATE_EVENT_ERROR = 'CREATE_EVENT_ERROR';
// Get Events Actions
export const FETCHING_EVENTS = 'FETCHING_EVENTS';
export const RECEIVED_EVENTS = 'RECEIVED_EVENTS';
export const FETCHING_EVENTS_ERROR = 'EVENT_ERROR';
