export const TOKEN_EXPIRED = 'TOKEN_EXPIRED';

// Signup Actions Types
export const REQUEST_SIGNUP_USER = 'REQUEST_REGISTER_USER';
export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';

// Create Center Action Types
export const RECIEVED_CENTER_CONTACTS = 'RECIEVED_CENTER_CONTACTS';
export const FETCHING_CENTER_CONTACTS = 'FETCHING_CENTER_CONTACTS';
