module.exports = [
  'It gives us great pleasure to introduce, Classique Events Place Pearl Hall. A one and a half acre piece of property, uniquely brick built with the state of the art facility within a well kept vicinity. It is spacious, fully airconditioned and highly insulated with capacity to host up to 500 guests in banquet settings and 1000 guests in theater settings. This makes it convenient for us to host both corporate and retail events in a serene environment. They can conveniently host weddings, corporate functions, parties, banquets, church services and more It further has the capacity to accommodate over 300 cars parked within the premises without obstructing free flow of traffic along the high way.',

  'Platinum Hall is Marquee tent located on a spacious landmass within the premises in a serene and secured environment of Ikeja with full AC. Our hall is suitable for all kinds of events with a capacity of 400 guests.',

  'Sapphire Hall is located on the first floor of the building with full AC and in a serene and secure environment. Sapphire hall is suitable for all kinds of events with a capacity of 150 guest.',

  'FM EVENT Centre is a perfect venue for you, whether for a wedding, Christmas party, product launch, meetings, conferences or entertainment events. Together with our experienced events managers and award winning hospitality, we ensure that your experience with us is extraordinary and truly memorable.',

  'Add a unique touch to your event at Tobol Event Centre. Have a grand event at our exquisite marquee. Be classy on your memorable day with state of the art decoration. It seats 500 persons in a banquet setting and 650 in a theatre setting. Facilities such as tables, chairs, rest rooms, changing room, air condition, 24 hour power supply, fans and reliable security are available just for you.',

  'Classy is just a tip of the iceberg with Sheba Centre. A Grand marquee setting aimed at pleasing you and granting all your wishes on that special day. Classy chandeliers to add glam to your day. It is located in a serene environment that is accessible from every part of Lagos. State of the art changing room and classy rest room after devouring the owambe delicacies await you. It seats comfortably 800 persons in banquet setting. A very spacious compound for flawless parking of cars is available for your guest. Tables, chairs, well-structured stage, 24 hour power supply, lighting, air condition, well-structured stage and maximum security is guaranteed.',

  'Knightbridge Hotels Big Hall is such a stunning place to be, taking into cognizance the spacious environment that allows for every guest to park their cars adequately. Talk less of the standard able bodied security personnels.Stepping into this multipurpose hall which can sit up to 120 guests banquet settings and 180 guests theatre settings; the cool atmosphere of the Knightbridge hall help guests feel comfortable as a result of the standard air conditioner placed in it, this is aided by the constant supply of power made available at the Knightbridge venue. This hall best suit any of your events, as this is obvious in the availability of a sound system, a projector system and a changing room. The chairs and tables as well help guests feel relaxed and comfortable.',
];
